### ISSUE TITLE
deepsort

### ISSUE THREAD

**Issue by wafaer** [pkzhou/PointSLOT#2]
@pkzhou 您好，请问您的deepsort模型是怎么生成的，能不能提供生成思路。在运行您的Pointslot时出现：stereo_kitti: /home/hermione/slam/src/PointSLOT/deepsort/src/featuretensor.cpp:76: void DS::FeatureTensor::loadEngine(std::string): Assertion `engine != nullptr' failed.

**Comment by pkzhou** [comment]
Hello，deepsort模型是通过TensorRT将onnx模型文件导出成的一个.engine文件。如您所见，我们这个project使用的TensorRT版本是8.4.0.6。如果您无法使用该版本，您可以自行下载deepsort的pytorch模型，转化为onnx文件后，用您的系统内核支持的TensorRT转化deepsort模型。当然，这个project里的TensorRT版本也需要换成相应的版本。
