### ISSUE TITLE
ThirdParties Version 

### ISSUE THREAD

**Issue by Tonny24Wang** [pkzhou/PointSLOT#4]
Could you list all the thirdpaty versions?  And necessay compiling setting is needed. I've tried to compile the source code in my computer, but it shows a lot of questions about compiling and linking .  
Thanks a lot !

**Comment by pkzhou** [comment]
It seems that you have solved this problem?

**Comment by Tonny24Wang** [comment]
Yes，thank you !&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 7, 2023 11:37 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [pkzhou/PointSLOT] ThirdParties Version  (Issue #4)




 
It seems that you have solved this problem?
